import './globals.css'
import { Fira_Code } from 'next/font/google'
import { BodyLayout } from './layouts/BodyLayout'

const firaCode = Fira_Code({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="pt-br">
      <body className={firaCode.className + " transition-colors delay-0 ease-in-out text-justify scroll-smooth min-h-screen w-full"}>
        <BodyLayout>
          {children}
        </BodyLayout>
      </body>
    </html>
  )
}
